
package tienda;

import clases.Electrodomestico;
import clases.Lavadora;
import clases.Television;
import javax.swing.JOptionPane;


public class Productos extends javax.swing.JFrame {

    
    Electrodomestico miElectrodomestico = new Electrodomestico();
    Lavadora miLavadora = new Lavadora();
    Television miTelevision = new Television();
    
    public Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        electrodomesticos = new javax.swing.JLabel();
        lavadoras = new javax.swing.JLabel();
        television = new javax.swing.JLabel();
        labelElectrodomesticos = new javax.swing.JLabel();
        labelLavadoras = new javax.swing.JLabel();
        labelTelevision = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/electrodomestico.png"))); // NOI18N

        electrodomesticos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        electrodomesticos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home-appliance.png"))); // NOI18N
        electrodomesticos.setText("Electrodomésticos:");

        lavadoras.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lavadoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lavadora.png"))); // NOI18N
        lavadoras.setText("Lavadoras:");

        television.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        television.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/monitor-de-tv.png"))); // NOI18N
        television.setText("Television:");

        labelElectrodomesticos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelElectrodomesticos.setText("0");

        labelLavadoras.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelLavadoras.setText("0");

        labelTelevision.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelTelevision.setText("0");

        total.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        total.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/todos.png"))); // NOI18N
        total.setText("Total:");

        labelTotal.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelTotal.setText("0");

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnIniciar.setBackground(new java.awt.Color(153, 153, 255));
        btnIniciar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro.png"))); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.setBorder(null);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(logo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(television, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(electrodomesticos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lavadoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelLavadoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelElectrodomesticos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTelevision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(logo)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(electrodomesticos)
                    .addComponent(labelElectrodomesticos))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lavadoras)
                    .addComponent(labelLavadoras))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(television)
                    .addComponent(labelTelevision))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total)
                    .addComponent(labelTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       
        this.dispose();
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        
        Electrodomestico[] electrodomesticos = new Electrodomestico[10];
        
        double totalElectrodomesticos = 0;
        double totalLavadoras = 0;
        double totalTelevisiones = 0;
        double sumaTotal = 0;
        
        // Bucle para pedir los datos de cada objeto y calcular el precio final
        
        for (int i = 0; i < 10; i++) {
            
            String[] opciones = {"Electrodoméstico", "Lavadora", "Televisión"};
            int opcion = JOptionPane.showOptionDialog(null, "¿Qué tipo de electrodoméstico desea crear?", "Crear Electrodoméstico",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opciones, opciones[0]);
            
            if (opcion == 0) {
                
                double precioBase = Double.parseDouble(JOptionPane.showInputDialog(null, "Introduce el precio base:"));
                double peso = Double.parseDouble(JOptionPane.showInputDialog(null, "Introduce el peso:"));
                String color = JOptionPane.showInputDialog(null, "Introduce el color:");
                String consumoEnergetico = JOptionPane.showInputDialog(null, "Introduce el consumo energético (letra entre A y F):");
                
                Electrodomestico electrodomestico = new Electrodomestico(precioBase, color, consumoEnergetico.charAt(0), peso);
                electrodomesticos[i] = electrodomestico;
                
                sumaTotal += electrodomestico.precioFinal();
                
                double precioFinal = electrodomestico.precioFinal();
                totalElectrodomesticos += precioFinal;
                
 
                labelElectrodomesticos.setText(String.valueOf(totalElectrodomesticos));
                labelLavadoras.setText(String.valueOf(totalLavadoras));
                labelTelevision.setText(String.valueOf(totalTelevisiones));            
                labelTotal.setText(String.valueOf(sumaTotal));
                

            } else if (opcion == 1) {
                
                double precioBase = Double.parseDouble(JOptionPane.showInputDialog(null, "Introduce el precio base:"));
                double peso = Double.parseDouble(JOptionPane.showInputDialog(null, "Introduce el peso:"));
                String color = JOptionPane.showInputDialog(null, "Introduce el color:");
                String consumoEnergetico = JOptionPane.showInputDialog(null, "Introduce el consumo energético (letra entre A y F):");
                int carga = Integer.parseInt(JOptionPane.showInputDialog(null, "Introduce la carga:"));
                
                Lavadora lavadora = new Lavadora(precioBase, color, consumoEnergetico.charAt(0), peso, carga);
                electrodomesticos[i] = lavadora;
                
  
                if (lavadora instanceof Lavadora) {
                    double precioFinal = lavadora.precioFinal();
                    totalLavadoras += precioFinal;
                    
                    sumaTotal += lavadora.precioFinal();
                }
                
                labelElectrodomesticos.setText(String.valueOf(totalElectrodomesticos));
                labelLavadoras.setText(String.valueOf(totalLavadoras));
                labelTelevision.setText(String.valueOf(totalTelevisiones));
                labelTotal.setText(String.valueOf(sumaTotal));
                 
                
            } else if (opcion == 2) {
                
                double precioBase = Double.parseDouble(JOptionPane.showInputDialog(null, "Introduce el precio base:"));
                double peso = Double.parseDouble(JOptionPane.showInputDialog(null, "Introduce el peso:"));
                String color = JOptionPane.showInputDialog(null, "Introduce el color:");
                String consumoEnergetico = JOptionPane.showInputDialog(null, "Introduce el consumo energético (letra entre A y F):");
                int resolucion = Integer.parseInt(JOptionPane.showInputDialog(null, "Introduce la resolución en pulgadas:"));
                boolean sintonizadorTDT = Boolean.parseBoolean(JOptionPane.showInputDialog(null, "¿Tiene sintonizador TDT? (true/false)"));
                
                Television television = new Television(precioBase, color, consumoEnergetico.charAt(0), peso, resolucion, sintonizadorTDT);
                electrodomesticos[i] = television;
                  
                
                if (television instanceof Television) {
                    double precioFinal = television.precioFinal();
                    totalTelevisiones += precioFinal;
                    
                    sumaTotal += television.precioFinal();
                    
                }
                
                labelElectrodomesticos.setText(String.valueOf(totalElectrodomesticos));
                labelLavadoras.setText(String.valueOf(totalLavadoras));
                labelTelevision.setText(String.valueOf(totalTelevisiones));
                labelTotal.setText(String.valueOf(sumaTotal));
                
            }
       
        }
               
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel electrodomesticos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelElectrodomesticos;
    private javax.swing.JLabel labelLavadoras;
    private javax.swing.JLabel labelTelevision;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel lavadoras;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel television;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
